apiVersion: v1
kind: Service
metadata:
  name: intranet-newdeal-service
spec:
  selector:
    app: intranet-newdeal
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080