name: CD Pipeline - Prod

on:
  push:
    branches: [prod]

env:
  IMAGE_NAME: intranet-newdeal
  IMAGE_TAG: 1.0.0
  DOCKER_REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:

  # ===============================
  # JOB 1 - SCAN SECURITE
  # ===============================
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Login Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | \
          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Pull image
        run: |
          docker pull ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Scan Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: table
          exit-code: '0'
          severity: 'LOW,MEDIUM,HIGH,CRITICAL'
          scanners: 'vuln,secret'

  # ===============================
  # JOB 2 - DEPLOIEMENT
  # ===============================
  deploy:
    runs-on: runner_prod
    needs: scan
    steps:
      - name: Login Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | \
          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Pull image
        run: |
          docker pull ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Stop existing container
        run: docker stop intranet-app || true

      - name: Remove old container
        run: docker rm intranet-app || true

      - name: Run container
        run: |
          docker run -d \
            -p 80:80 \
            --name intranet-app \
            --restart always \
            ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Verify deployment
        run: |
          docker ps | grep intranet-app